### ISSUE TITLE
API Parameters duplicating when switching tabs

### ISSUE THREAD

**Issue by Haxiz** [testingisdocumenting/znai#954] opened 2022-08-21 23:22 UTC
If you have two tabs containing API Parameters and switch between them, the first entry of the second tab gets added once again to the content of both tabs.

Example:
`````
# /forward
This command will skip the song forward by the time given.

````tabs
Options:
```api-parameters
time, Required, "The amount of time to forward. Time is in this format: 1m29s (1 minute and 29s), for example."
```

Requirements:
This command requires either [**Admin** or **DJ** permissions](commands/permissions#intro).

Examples:
```api-parameters
"", "", "/forward `time:`2m"
"", "", "/forward `time:`1m29s"
```
````
`````
Switching back and forth:
![image](https://user-images.githubusercontent.com/31944205/185815165-7baa0a3e-b85c-46f5-8919-4d0e44e9a4fd.png)
![image](https://user-images.githubusercontent.com/31944205/185815172-05d46264-4559-4715-890d-15eb5fe9e720.png)
![image](https://user-images.githubusercontent.com/31944205/185815174-69a11f89-6d5c-48e3-9107-695eacee3f80.png)
![image](https://user-images.githubusercontent.com/31944205/185815176-3f1191cb-bd23-44d2-acac-310a670a3e6c.png)

**Comment by MykolaGolubyev** [comment] 2022-08-21 23:40
Uh that doesn't look good. On it! 
thank you for the detailed report

**Comment by MykolaGolubyev** [comment] 2022-08-21 23:41
slightly related, curios, did you try open api Znai support?

**Comment by MykolaGolubyev** [comment] 2022-08-21 23:47
what version of znai do you use? can't seem to reproduce it.

**Comment by Haxiz** [comment] 2022-08-21 23:54
I used version 1.59 i got from https://testingisdocumenting.org/znai/introduction/getting-started/#cli-download
Also no, I didn't try the open api support. All the pages I'm working on I'm doing by hand

**Comment by Haxiz** [comment] 2022-08-21 23:55
if its worth mentioning, this is happening on the preview version. I didn't try it on a built version

**Comment by MykolaGolubyev** [comment] 2022-08-21 23:55
does it go away when you restart preview?

**Comment by Haxiz** [comment] 2022-08-21 23:57
it still happens even after restarting preview

**Comment by Haxiz** [comment] 2022-08-21 23:59
If i stack them up
![image](https://user-images.githubusercontent.com/31944205/185816703-a0e59ec2-90c3-4817-bbac-28a1a6958e8d.png)
basically any change that's not opening another tab with api parameters restarts it, so in the case of this image switching to 'Requirements' and then back to 'Options' makes it go back to normal

**Comment by MykolaGolubyev** [comment] 2022-08-21 23:59
I wonder if by any chance you may have got a previous version by using sdkman or brew
to double check (if you haven't) could you run `znai --version`?

**Comment by Haxiz** [comment] 2022-08-22 00:01
![image](https://user-images.githubusercontent.com/31944205/185816867-8cb256c9-1597-4e5e-98c0-0ddbca07ba0e.png)

**Comment by MykolaGolubyev** [comment] 2022-08-22 00:02
could you please elaborate a bit more on steps to reproduce?

**Comment by MykolaGolubyev** [comment] 2022-08-22 00:06
oh wait never mind, I can repro it now

**Comment by MykolaGolubyev** [comment] 2022-08-22 00:24
fix is in pipeline. let me know how critical it is. I try to release once a month but can release more often if there are critical things.

The reason it doesn't work right now as expected is UI assumes unique parameter names but multiple empty names were provided.

if you give me a bit more info on what final look and feel you want to achieve I may come up with some options.

**Comment by Haxiz** [comment] 2022-08-22 00:33
thanks, its not world ending as I think I can work around it by only having one tab use api params. Though it would be nice to use multiple before we launch this out to the open. I also found another thing, but i'm making a different issue for it.

As far as the look we're going for https://www.mantaro.site/mantaro-wiki/commands/audio-commands this would be an example of what we're trying to do. Basically its command documentation.

In that page the first command you see (/forward) would probably be what we're aiming for, and want to apply to the others. The other commands have the previous version we were thinking of doing with bullet points.

It's very likely we'll also end up using a combination of what you see in the page, and some collapsing or multiline csv api parameters for the more complex commands.

**Comment by Haxiz** [comment] 2022-08-22 01:02
To expand a bit more on look and feel, I made an example of a more complex command on our doc.

Here is a version I can do right now without encountering the issue by using normal bullet points
`````
# /badges
Shows a list of your own badges or a list of the badges from the given user. A full list of the badges can be found [here](currency/badges).

````tabs
Subcommands:
* `Info`: Shows info about a badge.
* `List`: Lists all the obtainable badges.
* `Show`: Show your badge list, or someone else's badge list. 

Options:
```api-parameters
Info, Click me!, "Options for the `Info` Subcommand"
Info.badge, "Required", "The badge to check info for"
Show, Click me!, "Options for the `Show` Subcommand"
Show.user, "Optional", "The user to check. If none, you."
Show.brief, "Optional", "Whether to show this in brief format. Default is false."
```

Requirements:
* This command requires [**Embed**, **Emotes** and **Reactions** permissions](commands/permissions#intro).

Examples:
* /badges show
* /badges show `user:`@Kodehawa#3457
* /badges list
* /badges info `badge:`Donator
````
`````
It uses only 1 api-parameters, which avoids the issue.

Here is another version that basically uses api-parameters on all tabs
`````
# /badges
Shows a list of your own badges or a list of the badges from the given user. A full list of the badges can be found [here](currency/badges).

````tabs
Subcommands:
```api-parameters
Info, "", "Shows info about a badge."
List, "", "Lists all the obtainable badges."
Show, "", "Show your badge list, or someone else's badge list." 
```

Options:
```api-parameters
Info, Click me!, "Options for the `Info` Subcommand"
Info.badge, "Required", "The badge to check info for."
Show, Click me!, "Options for the `Show` Subcommand"
Show.user, "Optional", "The user to check. If none, you."
Show.brief, "Optional", "Whether to show this in brief format. Default is false."
```

Requirements:
* This command requires the [**Emotes** permission](commands/permissions#intro).

Examples:
```api-parameters
"", "", "/badges show"
"", "", "/badges show `user:`@Kodehawa#3457"
"", "", "/badges list"
"", "", "/badges info `badge:`Donator"
```
````
`````
The main appeal to us right now of using more api-parameters would probably be the spacing it provides when compared to normal bullet points, as well as the option of nested information.

**Comment by MykolaGolubyev** [comment] 2022-08-22 01:05
thanks. this is clever!
The culprit is the examples tab that uses empty names and that's what confuses UI.
is the API for command lines?

**Comment by Haxiz** [comment] 2022-08-22 01:08
The docs are for a Discord bot. We currently have a wiki on Github, but found this tool and all the better options it has so we decided to move. It basically documents all of the bot's commands, as well as items, tutorials and so on.

**Comment by Haxiz** [comment] 2022-08-22 01:10
This is what we currently have on our Github wiki
![image](https://user-images.githubusercontent.com/31944205/185820279-36942cad-cb5d-4346-9559-00ed8aeee916.png)
as you can see, it can be greatly improved and reduced

**Comment by MykolaGolubyev** [comment] 2022-08-22 01:11
Got it. Thanks you
Most likely will release a patch due to another issue you found
Need to think a bit more how to better render examples. Using api params without names is not the original intend.

**Comment by Haxiz** [comment] 2022-08-22 01:15
Incidentally, while making that previous example I found another issue! I'll make a different one as to not spam this issue with something different.
Thanks for all of your help!

**Comment by MykolaGolubyev** [comment] 2022-08-22 01:16
Thank you for providing new use cases and reporting. Really appreciate it!

**Closed** 2022-08-22 12:07 UTC

**Comment by MykolaGolubyev** [comment] 2022-08-23 01:03
released https://testingisdocumenting.org/znai/release-notes/2022/#1591

**Comment by Haxiz** [comment] 2022-08-23 03:28
thanks for the help!

**Comment by MykolaGolubyev** [comment] 2022-08-25 16:40
@Haxiz any chance you can add a small entry to https://github.com/testingisdocumenting/znai/discussions/824 ?
