### ISSUE TITLE
cannot use links to auto sections from open api

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/znai#217] opened 2019-07-02 13:54 UTC
If one uses `:include-open-api: <path> {autoSection: true}`, one cannot create a link to those sections.  It gives a generic "can't find a page associated with" error and the following stack trace:
```
at com.twosigma.documentation.website.WebSiteDocStructure.validateCollectedLinks(WebSiteDocStructure.java:41)
    at com.twosigma.documentation.website.WebSite.validateCollectedLinks(WebSite.java:466)
    at com.twosigma.documentation.website.WebSite.generate(WebSite.java:146)
    at com.twosigma.documentation.website.WebSite$Configuration.deployTo(WebSite.java:602)
    at com.twosigma.documentation.cli.DocumentationCliApp.generateDocs(DocumentationCliApp.java:104)
    at com.twosigma.documentation.cli.DocumentationCliApp.start(DocumentationCliApp.java:66)
    at com.twosigma.documentation.cli.DocumentationCliApp.start(DocumentationCliApp.java:37)
    at com.twosigma.documentation.cli.DocumentationCliApp.main(DocumentationCliApp.java:42)
```

**Comment by MykolaGolubyev** [comment] 2021-08-09 22:08
can't reproduce anymore. could have been fixed by some other PRs
let me know if it is still an issue

**Closed by MykolaGolubyev** 2021-08-09 22:08 UTC
